services:
  postgres:
    image: 'postgres:latest'
    container_name: 'librarydb'
    environment:
      - 'POSTGRES_DB=library'
      - 'POSTGRES_PASSWORD=library'
      - 'POSTGRES_USER=library'
    ports:
      - '5432:5432'

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    container_name: 'libraryadmin'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '15432:80'
    depends_on:
      - postgres